import Head from "next/head";
import Image from "next/image";

// import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <title>Apply to Saivest</title>
        <meta name="About Us" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image className="flex w-full h-auto"
          src="https://media.istockphoto.com/id/1068752548/photo/team-of-business-people-working-together-in-the-office-teamwork-double-exposure.jpg?s=612x612&w=0&k=20&c=6T-r6GRRdjipq7BLDDKKS1Z-WIj_5ov2Z6ylNnu0mRw="
          alt="alt"
          width={1224}
          height={490} />
        <div className="container flex flex-col gap-12 py-6 overflow-x-auto">
          {/*
              TODO
              this is where we will have an about us page that discusses the company and the open job offerings
              add a banner and sub panel for contact us type info then just like a solid block of text with all the info
              because route is static
            */}
          <div>


          </div>

        </div>
      </main>
      <text_box_template text="jow" />
    </>
  );
}
