import Head from "next/head";

// import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Apply to Saivest</title>
        <meta name="About Us" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-x-auto">
        <div className="flex bg-white bg-gradient-to-b from-stone-800 h-screen  w-screen items-center p-20">
          <h1 className=" animate-typing overflow-hidden whitespace-nowrap text-base md:text-8xl text-white font-bold">
            Financial Tech Done Right.
          </h1>
        </div>
        <div className="flex justify-center">
        <div className="flex justify-center border-t-4 border-stone-900 w-11/12 h-screen">
          hello world
        </div>
        </div>
      </main>
    </>
  );
}

// TODO
// this is where we will have an about us page that discusses the company and the open job offerings
// add a banner and sub panel for contact us type info then just like a solid block of text with all the info
// because route is static
