import Head from "next/head";

// import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Apply to Saivest</title>
        <meta name="About Us" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col gap-12 px-4 py-16 ">
          {/* TODO */}
          <p>
          this is where we will have an about us page that discusses the company and the open job offerings
          </p>
          
        </div>
      </main>
    </>
  );
}
